<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AlumniRegistrationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('alumni_registrations')->delete();
        
        \DB::table('alumni_registrations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'full_name' => 'Md.Washim Akram',
                'email' => 'washimakram013099@gmail.com',
                'phone' => '01309903313',
                'profile_image' => 'alumni/profiles/iaSgd5uHVMZesafhF17IqFS28eBe0HPMjpdYz76C.jpg',
                'student_id' => '0242310005341134',
                'department' => 'SWE',
                'batch' => '40',
                'graduation_year' => '2022',
                'current_position' => 'Senior Ai Engineer',
                'subtitle' => NULL,
                'company' => 'Goggle',
                'badge_text' => NULL,
                'badge_style' => NULL,
                'top_img_class' => NULL,
                'profile_img_class' => NULL,
                'container_class' => NULL,
                'company_logo' => 'alumni/logos/ewbVUQkfXOdEIMfdGCLzb7oeti6yP2qe6AbPTjj0.png',
                'category' => 'software-engineering',
                'linkedin_url' => 'https://www.linkedin.com/in/washim-akram-a60a72361/',
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 1,
                'admin_note' => 'Approved',
                'created_at' => '2026-03-22 22:20:33',
                'updated_at' => '2026-04-11 11:20:26',
            ),
            1 => 
            array (
                'id' => 2,
                'full_name' => 'Test Approval',
                'email' => 'test@approve.com',
                'phone' => NULL,
                'profile_image' => NULL,
                'student_id' => '123',
                'department' => 'CSE',
                'batch' => '1',
                'graduation_year' => '2020',
                'current_position' => 'Dev',
                'subtitle' => NULL,
                'company' => 'Google',
                'badge_text' => NULL,
                'badge_style' => NULL,
                'top_img_class' => NULL,
                'profile_img_class' => NULL,
                'container_class' => NULL,
                'company_logo' => NULL,
                'category' => 'software-engineering',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'pending',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-03-31 08:21:51',
                'updated_at' => '2026-03-31 08:21:51',
            ),
            2 => 
            array (
                'id' => 3,
                'full_name' => 'Md. Imdadullah Siddiquee',
                'email' => 'imdadullah@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_journalism.png',
                'student_id' => 'AL-001',
                'department' => 'Journalism',
                'batch' => 'N/A',
                'graduation_year' => '2015',
                'current_position' => 'Chief Reporter at ATN Bangla',
                'subtitle' => NULL,
                'company' => 'ATN Bangla',
                'badge_text' => 'PREMIUM',
                'badge_style' => NULL,
                'top_img_class' => 'field-img journalism-bg',
                'profile_img_class' => 'profile-img journalism-profile',
                'container_class' => NULL,
                'company_logo' => NULL,
                'category' => 'journalism',
                'linkedin_url' => NULL,
                'card_bg_image' => 'alumni/alumni_journalism.png',
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:10:58',
            ),
            3 => 
            array (
                'id' => 4,
                'full_name' => 'Md. Harun-Ur-Rashid',
                'email' => 'harun@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_cse_harun.png',
                'student_id' => 'AL-002',
                'department' => 'Computer Science and Engineering',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Software Engineer at Upay',
                'subtitle' => NULL,
                'company' => 'Upay',
                'badge_text' => 'PREMIUM',
                'badge_style' => NULL,
                'top_img_class' => 'img-contain-70',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'company_logo' => 'alumni/upay_logo.png',
                'category' => 'software-engineering',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            4 => 
            array (
                'id' => 5,
                'full_name' => 'F. M. Javed Mehedi Shamrat',
                'email' => 'javed@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_swe_javed.png',
                'student_id' => 'AL-003',
                'department' => 'Software Engineering',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Visiting Researcher at DIU & Research Assistant at USQ, Australia',
            'subtitle' => 'World\'s Top 2% Scientist (Stanford List 2024-25)',
                'company' => 'DIU & USQ',
                'badge_text' => 'PREMIUM',
                'badge_style' => 'badge-gold',
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'company_logo' => NULL,
                'category' => 'software-engineering',
                'linkedin_url' => NULL,
                'card_bg_image' => 'alumni/diu_building.png',
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            5 => 
            array (
                'id' => 6,
                'full_name' => 'Tofa Firdaosi Mim',
                'email' => 'mim@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_nfe_2.png',
                'student_id' => 'AL-004',
                'department' => 'Nutrition and Food Engineering',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Area Nutrition Officer at Nestle Bangladesh PLC',
                'subtitle' => NULL,
                'company' => 'Nestle Bangladesh PLC',
                'badge_text' => 'PREMIUM',
                'badge_style' => NULL,
                'top_img_class' => 'img-contain-80',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'company_logo' => 'alumni/nestle_logo_blue.png',
                'category' => 'nfe',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            6 => 
            array (
                'id' => 7,
                'full_name' => 'Sayma Sultana Sworna',
                'email' => 'sworna@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_nfe_1.png',
                'student_id' => 'AL-005',
                'department' => 'Nutrition and Food Engineering',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Area Nutrition Officer at Nestle Bangladesh PLC',
                'subtitle' => NULL,
                'company' => 'Nestle Bangladesh PLC',
                'badge_text' => 'PREMIUM',
                'badge_style' => NULL,
                'top_img_class' => 'img-contain-80',
                'profile_img_class' => 'profile-img profile-pos-15',
                'container_class' => 'card-top-logo-container',
                'company_logo' => 'alumni/nestle_logo.png',
                'category' => 'nfe',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            7 => 
            array (
                'id' => 8,
                'full_name' => 'Md. Faysal Hasan',
                'email' => 'faysal@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_textile_1.png',
                'student_id' => 'AL-006',
                'department' => 'Textile Engineering',
                'batch' => '45th BCS',
                'graduation_year' => 'N/A',
            'current_position' => 'Assistant Commissioner of Taxes (BCS)',
                'subtitle' => NULL,
                'company' => 'Bangladesh Government',
                'badge_text' => 'PREMIUM',
                'badge_style' => 'badge-red',
                'top_img_class' => 'img-contain-45',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'company_logo' => 'alumni/gov_seal_bd.png',
                'category' => 'textile',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            8 => 
            array (
                'id' => 9,
                'full_name' => 'Alumni Graduate',
                'email' => 'alumni1@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_bba_1.png',
                'student_id' => 'AL-007',
                'department' => 'BBA',
                'batch' => 'N/A',
                'graduation_year' => '2016',
                'current_position' => 'Commercial Manager at IMCD Group',
                'subtitle' => NULL,
                'company' => 'IMCD Group',
                'badge_text' => 'PREMIUM',
                'badge_style' => NULL,
                'top_img_class' => 'img-contain-70',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'company_logo' => 'alumni/imcd_logo.png',
                'category' => 'bba',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            9 => 
            array (
                'id' => 10,
                'full_name' => 'Mr. Joy Saha ACA',
                'email' => 'joy@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_bba_joy.png',
                'student_id' => 'AL-008',
                'department' => 'Business Administration',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Head of Tax Advisory & VAT at ACE Advisory',
                'subtitle' => NULL,
                'company' => 'ACE Advisory',
                'badge_text' => 'PREMIUM',
                'badge_style' => NULL,
                'top_img_class' => 'img-contain-50',
                'profile_img_class' => 'profile-img journalism-profile',
                'container_class' => 'card-top-logo-container',
                'company_logo' => 'alumni/ace_logo.png',
                'category' => 'bba',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            10 => 
            array (
                'id' => 11,
                'full_name' => 'Md. Mozahidul Islam',
                'email' => 'mozahidul@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_pharmacy_2.png',
                'student_id' => 'AL-009',
                'department' => 'Pharmacy',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
            'current_position' => 'Officer - Product Development (Analytical) at Renata PLC',
                'subtitle' => NULL,
                'company' => 'Renata PLC',
                'badge_text' => 'PREMIUM',
                'badge_style' => NULL,
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'company_logo' => 'alumni/renata_logo.png',
                'category' => 'pharmacy',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            11 => 
            array (
                'id' => 12,
                'full_name' => 'Md. Tanjimul Ahasan',
                'email' => 'tanjimul@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/alumni_pharmacy_1.png',
                'student_id' => 'AL-010',
                'department' => 'Pharmacy',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
            'current_position' => 'Senior Executive (Business Development) at Isabah Plastic Industries Ltd.',
                'subtitle' => NULL,
                'company' => 'Isabah Plastic Industries Ltd.',
                'badge_text' => 'EXECUTIVE',
                'badge_style' => NULL,
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => 'profile-img profile-pos-25',
                'container_class' => 'card-top-logo-container',
                'company_logo' => 'alumni/alumni_pharmacy_1.png',
                'category' => 'pharmacy',
                'linkedin_url' => NULL,
                'card_bg_image' => NULL,
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:12:15',
            ),
            12 => 
            array (
                'id' => 13,
                'full_name' => 'Jason Williams',
                'email' => 'jason@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/profile_1.png',
                'student_id' => 'AL-011',
                'department' => 'CSE',
                'batch' => 'N/A',
                'graduation_year' => '2018',
                'current_position' => 'Senior Software Engineer at Google',
                'subtitle' => NULL,
                'company' => 'Google',
                'badge_text' => 'SOFTWARE ENGINEER',
                'badge_style' => NULL,
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => NULL,
                'container_class' => NULL,
                'company_logo' => NULL,
                'category' => 'software-engineering',
                'linkedin_url' => NULL,
                'card_bg_image' => 'alumni/alumni_tech_bg.png',
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:10:58',
            ),
            13 => 
            array (
                'id' => 14,
                'full_name' => 'Pamela Foster',
                'email' => 'pamela@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/profile_2.png',
                'student_id' => 'AL-012',
                'department' => 'SWE',
                'batch' => 'N/A',
                'graduation_year' => '2019',
                'current_position' => 'UX Design Lead at Adobe',
                'subtitle' => NULL,
                'company' => 'Adobe',
                'badge_text' => 'UX DESIGN LEAD',
                'badge_style' => NULL,
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => NULL,
                'container_class' => NULL,
                'company_logo' => NULL,
                'category' => 'uiux-design',
                'linkedin_url' => NULL,
                'card_bg_image' => 'alumni/alumni_tech_bg.png',
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:10:58',
            ),
            14 => 
            array (
                'id' => 15,
                'full_name' => 'Rose Simmons',
                'email' => 'rose@example.com',
                'phone' => NULL,
                'profile_image' => 'alumni/profile_1.png',
                'student_id' => 'AL-013',
                'department' => 'BBA',
                'batch' => 'N/A',
                'graduation_year' => '2020',
                'current_position' => 'Financial Analyst at Goldman Sachs',
                'subtitle' => NULL,
                'company' => 'Goldman Sachs',
                'badge_text' => 'FINANCIAL ANALYST',
                'badge_style' => NULL,
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => NULL,
                'container_class' => NULL,
                'company_logo' => NULL,
                'category' => 'finance',
                'linkedin_url' => NULL,
                'card_bg_image' => 'alumni/alumni_tech_bg.png',
                'status' => 'approved',
                'is_notified' => 0,
                'admin_note' => NULL,
                'created_at' => '2026-04-10 22:08:36',
                'updated_at' => '2026-04-10 22:10:58',
            ),
        ));
        
        
    }
}