<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AlumniRegistration;

class AlumniSeeder extends Seeder
{
    public function run()
    {
        $alumniData = [
            [
                'full_name' => 'Md. Imdadullah Siddiquee',
                'email' => 'imdadullah@example.com',
                'student_id' => 'AL-001',
                'department' => 'Journalism',
                'batch' => 'N/A',
                'graduation_year' => '2015',
                'current_position' => 'Chief Reporter at ATN Bangla',
                'company' => 'ATN Bangla',
                'category' => 'journalism',
                'badge_text' => 'PREMIUM',
                'profile_image' => 'alumni/alumni_journalism.png',
                'card_bg_image' => 'alumni/alumni_journalism.png',
                'top_img_class' => 'field-img journalism-bg',
                'profile_img_class' => 'profile-img journalism-profile',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Md. Harun-Ur-Rashid',
                'email' => 'harun@example.com',
                'student_id' => 'AL-002',
                'department' => 'Computer Science and Engineering',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Software Engineer at Upay',
                'company' => 'Upay',
                'category' => 'software-engineering',
                'badge_text' => 'PREMIUM',
                'profile_image' => 'alumni/alumni_cse_harun.png',
                'company_logo' => 'alumni/upay_logo.png',
                'top_img_class' => 'img-contain-70',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'F. M. Javed Mehedi Shamrat',
                'email' => 'javed@example.com',
                'student_id' => 'AL-003',
                'department' => 'Software Engineering',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Visiting Researcher at DIU & Research Assistant at USQ, Australia',
                'company' => 'DIU & USQ',
                'category' => 'software-engineering',
                'badge_text' => 'PREMIUM',
                'badge_style' => 'badge-gold',
                'subtitle' => "World's Top 2% Scientist (Stanford List 2024-25)",
                'profile_image' => 'alumni/alumni_swe_javed.png',
                'card_bg_image' => 'alumni/diu_building.png',
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Tofa Firdaosi Mim',
                'email' => 'mim@example.com',
                'student_id' => 'AL-004',
                'department' => 'Nutrition and Food Engineering',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Area Nutrition Officer at Nestle Bangladesh PLC',
                'company' => 'Nestle Bangladesh PLC',
                'category' => 'nfe',
                'badge_text' => 'PREMIUM',
                'profile_image' => 'alumni/alumni_nfe_2.png',
                'company_logo' => 'alumni/nestle_logo_blue.png',
                'top_img_class' => 'img-contain-80',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Sayma Sultana Sworna',
                'email' => 'sworna@example.com',
                'student_id' => 'AL-005',
                'department' => 'Nutrition and Food Engineering',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Area Nutrition Officer at Nestle Bangladesh PLC',
                'company' => 'Nestle Bangladesh PLC',
                'category' => 'nfe',
                'badge_text' => 'PREMIUM',
                'profile_image' => 'alumni/alumni_nfe_1.png',
                'company_logo' => 'alumni/nestle_logo.png',
                'top_img_class' => 'img-contain-80',
                'profile_img_class' => 'profile-img profile-pos-15',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Md. Faysal Hasan',
                'email' => 'faysal@example.com',
                'student_id' => 'AL-006',
                'department' => 'Textile Engineering',
                'batch' => '45th BCS',
                'graduation_year' => 'N/A',
                'current_position' => 'Assistant Commissioner of Taxes (BCS)',
                'company' => 'Bangladesh Government',
                'category' => 'textile',
                'badge_text' => 'PREMIUM',
                'badge_style' => 'badge-red',
                'profile_image' => 'alumni/alumni_textile_1.png',
                'company_logo' => 'alumni/gov_seal_bd.png',
                'top_img_class' => 'img-contain-45',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Alumni Graduate',
                'email' => 'alumni1@example.com',
                'student_id' => 'AL-007',
                'department' => 'BBA',
                'batch' => 'N/A',
                'graduation_year' => '2016',
                'current_position' => 'Commercial Manager at IMCD Group',
                'company' => 'IMCD Group',
                'category' => 'bba',
                'badge_text' => 'PREMIUM',
                'profile_image' => 'alumni/alumni_bba_1.png',
                'company_logo' => 'alumni/imcd_logo.png',
                'top_img_class' => 'img-contain-70',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Mr. Joy Saha ACA',
                'email' => 'joy@example.com',
                'student_id' => 'AL-008',
                'department' => 'Business Administration',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Head of Tax Advisory & VAT at ACE Advisory',
                'company' => 'ACE Advisory',
                'category' => 'bba',
                'badge_text' => 'PREMIUM',
                'profile_image' => 'alumni/alumni_bba_joy.png',
                'company_logo' => 'alumni/ace_logo.png',
                'top_img_class' => 'img-contain-50',
                'profile_img_class' => 'profile-img journalism-profile',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Md. Mozahidul Islam',
                'email' => 'mozahidul@example.com',
                'student_id' => 'AL-009',
                'department' => 'Pharmacy',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Officer - Product Development (Analytical) at Renata PLC',
                'company' => 'Renata PLC',
                'category' => 'pharmacy',
                'badge_text' => 'PREMIUM',
                'profile_image' => 'alumni/alumni_pharmacy_2.png',
                'company_logo' => 'alumni/renata_logo.png',
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => 'profile-img profile-pos-10',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Md. Tanjimul Ahasan',
                'email' => 'tanjimul@example.com',
                'student_id' => 'AL-010',
                'department' => 'Pharmacy',
                'batch' => 'N/A',
                'graduation_year' => 'N/A',
                'current_position' => 'Senior Executive (Business Development) at Isabah Plastic Industries Ltd.',
                'company' => 'Isabah Plastic Industries Ltd.',
                'category' => 'pharmacy',
                'badge_text' => 'EXECUTIVE',
                'profile_image' => 'alumni/alumni_pharmacy_1.png',
                'company_logo' => 'alumni/alumni_pharmacy_1.png',
                'top_img_class' => 'img-cover-full',
                'profile_img_class' => 'profile-img profile-pos-25',
                'container_class' => 'card-top-logo-container',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Jason Williams',
                'email' => 'jason@example.com',
                'student_id' => 'AL-011',
                'department' => 'CSE',
                'batch' => 'N/A',
                'graduation_year' => '2018',
                'current_position' => 'Senior Software Engineer at Google',
                'company' => 'Google',
                'category' => 'software-engineering',
                'badge_text' => 'SOFTWARE ENGINEER',
                'profile_image' => 'alumni/profile_1.png',
                'card_bg_image' => 'alumni/alumni_tech_bg.png',
                'top_img_class' => 'img-cover-full',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Pamela Foster',
                'email' => 'pamela@example.com',
                'student_id' => 'AL-012',
                'department' => 'SWE',
                'batch' => 'N/A',
                'graduation_year' => '2019',
                'current_position' => 'UX Design Lead at Adobe',
                'company' => 'Adobe',
                'category' => 'uiux-design',
                'badge_text' => 'UX DESIGN LEAD',
                'profile_image' => 'alumni/profile_2.png',
                'card_bg_image' => 'alumni/alumni_tech_bg.png',
                'top_img_class' => 'img-cover-full',
                'status' => 'approved',
            ],
            [
                'full_name' => 'Rose Simmons',
                'email' => 'rose@example.com',
                'student_id' => 'AL-013',
                'department' => 'BBA',
                'batch' => 'N/A',
                'graduation_year' => '2020',
                'current_position' => 'Financial Analyst at Goldman Sachs',
                'company' => 'Goldman Sachs',
                'category' => 'finance',
                'badge_text' => 'FINANCIAL ANALYST',
                'profile_image' => 'alumni/profile_1.png',
                'card_bg_image' => 'alumni/alumni_tech_bg.png',
                'top_img_class' => 'img-cover-full',
                'status' => 'approved',
            ],
        ];

        foreach ($alumniData as $data) {
            AlumniRegistration::updateOrCreate(
                ['email' => $data['email']],
                $data
            );
        }
    }
}
