<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SchedulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('schedules')->delete();
        
        \DB::table('schedules')->insert(array (
            0 => 
            array (
                'id' => 2,
                'course_code' => 'CSE421',
                'section' => NULL,
                'course_title' => 'Artificial Inteligense',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => NULL,
                'teacher_initial' => 'Fh',
                'department' => '',
                'batch' => '',
                'room_no' => '601',
                'day' => 'Monday',
                'time_slot' => '8.30 am-10.00 am',
                'created_at' => '2026-03-03 13:47:13',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'course_code' => 'DS332',
                'section' => 'B1',
                'course_title' => 'Introduction to Data science and data Management & Analysis',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'FH',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '601(AB3)',
                'day' => 'Sunday',
                'time_slot' => '8.30 am-10.00 am',
                'created_at' => '2026-03-03 14:05:41',
                'updated_at' => '2026-04-08 16:04:44',
                'user_id' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'course_code' => 'DS332',
                'section' => 'B2',
                'course_title' => 'Introduction to Data science and data Management & Analysis',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'FH',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '601(AB4)',
                'day' => 'Sunday',
                'time_slot' => '10.00 am-11.30 am',
                'created_at' => '2026-03-03 14:07:17',
                'updated_at' => '2026-04-08 16:05:04',
                'user_id' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'course_code' => 'DS441',
                'section' => 'B',
                'course_title' => 'Statistical Data Analysis',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'NM',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '101(AB4)',
                'day' => 'Sunday',
                'time_slot' => '1.00 pm-2.30 pm',
                'created_at' => '2026-03-03 14:08:40',
                'updated_at' => '2026-04-12 11:09:27',
                'user_id' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'course_code' => 'SE331',
                'section' => 'B2',
                'course_title' => 'Software Engineering Capstone Project',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'PC',
                'department' => '',
                'batch' => '',
            'room_no' => '106(AB3)',
                'day' => 'Wednesday',
                'time_slot' => '8.30 am-10.00 am',
                'created_at' => '2026-03-03 14:10:24',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'course_code' => 'DS332',
                'section' => 'B',
                'course_title' => 'Statistical Analysis',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'NM',
                'department' => 'SWE',
                'batch' => '231',
                'room_no' => '713',
                'day' => 'Monday',
                'time_slot' => '8.30 am-10.00 am',
                'created_at' => '2026-03-04 05:25:19',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'course_code' => 'DS441',
                'section' => 'B',
                'course_title' => 'Introduction to Data science and data Management & Analysis',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'FH',
                'department' => 'SWE',
                'batch' => '40',
                'room_no' => '713',
                'day' => 'Monday',
                'time_slot' => '1.00 pm-2.30 pm',
                'created_at' => '2026-03-04 06:19:57',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
            'course_code' => 'DS332(B2)',
                'section' => 'B',
                'course_title' => 'Statistical Analysis Lab',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'NM',
                'department' => 'SWE',
                'batch' => '40',
                'room_no' => '601',
                'day' => 'Tuesday',
                'time_slot' => '11.30 am-1.00 pm',
                'created_at' => '2026-03-04 06:21:37',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            8 => 
            array (
                'id' => 12,
            'course_code' => 'SE331(B1)',
                'section' => 'B',
                'course_title' => 'Software Engineering Capstone Project',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'PC',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '104(AB3)',
                'day' => 'Tuesday',
                'time_slot' => '8.30 am-10.00 am',
                'created_at' => '2026-03-04 07:02:40',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
            'course_code' => 'SE331(B1)',
                'section' => 'B',
                'course_title' => 'Software Engineering Capstone Project',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'PC',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '104(AB3)',
                'day' => 'Monday',
                'time_slot' => '8.30 am-10.00 am',
                'created_at' => '2026-03-04 07:03:24',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            10 => 
            array (
                'id' => 15,
            'course_code' => 'SE331(B2)',
                'section' => 'B',
                'course_title' => 'Software Engineering Capstone Project',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'PC',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '106(AB3)',
                'day' => 'Tuesday',
                'time_slot' => '2.30 pm-4.00 pm',
                'created_at' => '2026-03-04 07:05:26',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            11 => 
            array (
                'id' => 20,
                'course_code' => 'DS411',
                'section' => 'B',
                'course_title' => 'Statistical Data Analysis',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'FH',
                'department' => 'SWE',
                'batch' => '40',
                'room_no' => '811',
                'day' => 'Thursday',
                'time_slot' => '10.00 am-11.30 am',
                'created_at' => '2026-03-04 07:10:09',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            12 => 
            array (
                'id' => 21,
                'course_code' => 'DS331',
                'section' => 'B',
                'course_title' => 'Introduction to Data science and data Management & Analysis',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'FH',
                'department' => 'SWE',
                'batch' => '40',
                'room_no' => '713',
                'day' => 'Thursday',
                'time_slot' => '1.00 pm-2.30 pm',
                'created_at' => '2026-03-04 07:10:56',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            13 => 
            array (
                'id' => 22,
            'course_code' => 'DS332(B2)',
                'section' => 'B',
                'course_title' => 'Introduction to Data science and data Management & Analysis Lab',
                'type' => 'theory',
                'lab_section' => NULL,
                'major' => 'DS',
                'teacher_initial' => 'FH',
                'department' => 'SWE',
                'batch' => '40',
                'room_no' => '601',
                'day' => 'Thursday',
                'time_slot' => '2.30 pm-4.00 pm',
                'created_at' => '2026-03-04 07:11:41',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            14 => 
            array (
                'id' => 23,
                'course_code' => 'SE331',
                'section' => 'B',
                'course_title' => 'Software Engineering Capstone Project',
                'type' => 'lab',
                'lab_section' => 'B2',
                'major' => 'DS',
                'teacher_initial' => 'PC',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '107(AB3)',
                'day' => 'Wednesday',
                'time_slot' => '1.00 pm-2.30 pm',
                'created_at' => '2026-03-04 07:29:19',
                'updated_at' => '2026-03-04 14:06:23',
                'user_id' => NULL,
            ),
            15 => 
            array (
                'id' => 24,
                'course_code' => 'SE331',
                'section' => 'B',
                'course_title' => 'Software Engineering Capstone Project',
                'type' => 'lab',
                'lab_section' => 'B2',
                'major' => 'DS',
                'teacher_initial' => 'PC',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '107(AB3)',
                'day' => 'Wednesday',
                'time_slot' => '10.00 am-11.30 am',
                'created_at' => '2026-03-04 07:31:33',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            16 => 
            array (
                'id' => 25,
                'course_code' => 'DS412',
                'section' => 'B',
                'course_title' => 'Statistical Analysis Lab',
                'type' => 'lab',
                'lab_section' => 'B1',
                'major' => 'DS',
                'teacher_initial' => 'NM',
                'department' => 'SWE',
                'batch' => '40',
                'room_no' => '601',
                'day' => 'Wednesday',
                'time_slot' => '11.30 am-1.00 pm',
                'created_at' => '2026-03-04 07:32:45',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
            17 => 
            array (
                'id' => 26,
                'course_code' => 'SE331',
                'section' => 'B',
                'course_title' => 'Software Engineering Capstone Project',
                'type' => 'lab',
                'lab_section' => 'B1',
                'major' => 'DS',
                'teacher_initial' => 'PC',
                'department' => 'SWE',
                'batch' => '40',
            'room_no' => '107(AB3)',
                'day' => 'Wednesday',
                'time_slot' => '2.30 pm-4.00 pm',
                'created_at' => '2026-03-04 07:33:47',
                'updated_at' => '2026-03-04 14:02:19',
                'user_id' => NULL,
            ),
        ));
        
        
    }
}