<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Md.Washim Akram Mayaz',
                'email' => 'washimakram013099@gmail.com',
                'student_id' => '0242310005341134',
                'role' => 'admin',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '40',
                'semester' => '7th',
                'section' => 'B',
                'profile_image' => 'profile_images/iytPMNGOEOYHsXyCBIqSF3i5PC3VMDD2yHfT3dPf.jpg',
                'major' => 'DS',
                'email_verified_at' => NULL,
                'password' => '$2y$12$LIb1MQE2INwB8/HLyjh7huTi51duJKJxXzOn3bdxCnRRaqXT0kReG',
                'remember_token' => NULL,
                'created_at' => '2026-03-03 13:08:03',
                'updated_at' => '2026-05-04 23:43:34',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Tanveer Mazhar',
                'email' => 'islam2305341298@diu.edu.bd',
                'student_id' => '0242310005341298',
                'role' => 'admin',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '40',
                'semester' => '7th',
                'section' => 'B',
                'profile_image' => 'profile_images/sS2jWysbiIlm60UuD6ZFWRbjvb6KsuMNNkYjL4X8.jpg',
                'major' => 'DS',
                'email_verified_at' => NULL,
                'password' => '$2y$12$I7Y2kA6leVzYKZ3R.ulCE.Y62yc5385RmGuJkFyypGl4bBXSXy0Di',
                'remember_token' => NULL,
                'created_at' => '2026-03-03 16:45:09',
                'updated_at' => '2026-03-24 21:07:42',
            ),
            2 => 
            array (
                'id' => 6,
                'name' => 'Adnan Mayaz',
                'email' => 'mayaz23105341323@diu.edu.bd',
                'student_id' => '0242310005341323',
                'role' => 'cr',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '40',
                'semester' => '7th',
                'section' => 'B',
                'profile_image' => NULL,
                'major' => 'DS',
                'email_verified_at' => NULL,
                'password' => '$2y$12$4KoFovxmpBxJwbhl6tFe3uy.oIrkdz09Tvvgu2zBrQBY.Z8y.d2M6',
                'remember_token' => NULL,
                'created_at' => '2026-03-06 00:09:13',
                'updated_at' => '2026-03-25 23:37:36',
            ),
            3 => 
            array (
                'id' => 7,
                'name' => 'Md.Washim Akram',
                'email' => 'akram23105341134@diu.edu.bd',
                'student_id' => '0242310005341133',
                'role' => 'cr',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '40',
                'semester' => '7th',
                'section' => 'B',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$8r.3zt/P7dbiPG5Cf9zF9e4A1IJfcB7j7E1NwU3yUJdEZHdHTXXsi',
                'remember_token' => NULL,
                'created_at' => '2026-03-06 00:10:20',
                'updated_at' => '2026-03-06 11:33:19',
            ),
            4 => 
            array (
                'id' => 8,
                'name' => 'Tabassum Akter sadia',
                'email' => 'taba23105341289@diu.edu.bd',
                'student_id' => '0242310005341289',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '40',
                'semester' => '7th',
                'section' => 'B',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$aq86lLz7N56BGblpHFRUy.iwkoi4UShIRCQhHVr8Uf1o6fSZw7gTq',
                'remember_token' => NULL,
                'created_at' => '2026-03-06 12:16:32',
                'updated_at' => '2026-03-06 12:16:32',
            ),
            5 => 
            array (
                'id' => 9,
                'name' => 'Shihab Mahmud',
                'email' => 'mahmud23105341134@diu.edu.bd',
                'student_id' => '0242310005341026',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '40',
                'semester' => '7th',
                'section' => 'B',
                'profile_image' => 'profile_images/B8IbOY6uF2mh54u1zyK4inYqU81Xd65vWqqUIvhc.jpg',
                'major' => 'DS',
                'email_verified_at' => NULL,
                'password' => '$2y$12$D7khybelDUmmuzRhN6V1ueACqbckp7u.bpa.jhP0mCp2nwY/5lzta',
                'remember_token' => NULL,
                'created_at' => '2026-03-06 12:17:40',
                'updated_at' => '2026-03-30 23:36:22',
            ),
            6 => 
            array (
                'id' => 10,
                'name' => 'Test User',
                'email' => 'testuser@example.com',
                'student_id' => '12345',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'CSE',
                'batch' => '2024',
                'semester' => '1st',
                'section' => 'A',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$X6sqc/Z8L4E6Di6mHFSxReUYcWAezPjJ9yGV6R3HBAIuPMj15BPIO',
                'remember_token' => NULL,
                'created_at' => '2026-03-06 22:31:14',
                'updated_at' => '2026-03-06 22:31:14',
            ),
            7 => 
            array (
                'id' => 12,
                'name' => 'Lindsey Quigley',
                'email' => 'linqu10606901@diu.edu.bd',
                'student_id' => '10606901',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'LLB',
                'batch' => '39',
                'semester' => '3th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            8 => 
            array (
                'id' => 13,
                'name' => 'Hester Collier',
                'email' => 'hesco52139292@diu.edu.bd',
                'student_id' => '52139292',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'Pharmacy',
                'batch' => '38',
                'semester' => '4th',
                'section' => 'B',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            9 => 
            array (
                'id' => 14,
                'name' => 'Ruby Rempel',
                'email' => 'rubre35838874@diu.edu.bd',
                'student_id' => '35838874',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'LLB',
                'batch' => '42',
                'semester' => '1th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            10 => 
            array (
                'id' => 15,
                'name' => 'Bettye Price',
                'email' => 'betpr99919842@diu.edu.bd',
                'student_id' => '99919842',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'LLB',
                'batch' => '42',
                'semester' => '5th',
                'section' => 'B',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            11 => 
            array (
                'id' => 16,
                'name' => 'Louvenia Spinka',
                'email' => 'lousp16867281@diu.edu.bd',
                'student_id' => '16867281',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'English',
                'batch' => '39',
                'semester' => '5th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            12 => 
            array (
                'id' => 17,
                'name' => 'Scarlett Bins',
                'email' => 'scabi41202786@diu.edu.bd',
                'student_id' => '41202786',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'BBA',
                'batch' => '39',
                'semester' => '1th',
                'section' => 'C',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            13 => 
            array (
                'id' => 18,
                'name' => 'Rachael Beer',
                'email' => 'racbe54474768@diu.edu.bd',
                'student_id' => '54474768',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'BBA',
                'batch' => '38',
                'semester' => '1th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            14 => 
            array (
                'id' => 19,
                'name' => 'Jacques Jast',
                'email' => 'jacja64251562@diu.edu.bd',
                'student_id' => '64251562',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'BBA',
                'batch' => '42',
                'semester' => '3th',
                'section' => 'C',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            15 => 
            array (
                'id' => 20,
                'name' => 'Hanna Beatty',
                'email' => 'hanbe19635506@diu.edu.bd',
                'student_id' => '19635506',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'LLB',
                'batch' => '41',
                'semester' => '3th',
                'section' => 'C',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            16 => 
            array (
                'id' => 21,
                'name' => 'Quinten O\'Kon',
                'email' => 'quio\'60834824@diu.edu.bd',
                'student_id' => '60834824',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'CSE',
                'batch' => '42',
                'semester' => '2th',
                'section' => 'B',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            17 => 
            array (
                'id' => 22,
                'name' => 'Triston Bruen',
                'email' => 'tribr99745003@diu.edu.bd',
                'student_id' => '99745003',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '38',
                'semester' => '2th',
                'section' => 'C',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            18 => 
            array (
                'id' => 23,
                'name' => 'Hiram Huels',
                'email' => 'hirhu81365676@diu.edu.bd',
                'student_id' => '81365676',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'Pharmacy',
                'batch' => '38',
                'semester' => '3th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            19 => 
            array (
                'id' => 24,
                'name' => 'Quincy Carter',
                'email' => 'quica30121764@diu.edu.bd',
                'student_id' => '30121764',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'BBA',
                'batch' => '42',
                'semester' => '3th',
                'section' => 'C',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            20 => 
            array (
                'id' => 25,
                'name' => 'Odell Walter',
                'email' => 'odewa38176630@diu.edu.bd',
                'student_id' => '38176630',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'LLB',
                'batch' => '42',
                'semester' => '3th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            21 => 
            array (
                'id' => 26,
                'name' => 'Cleora Romaguera',
                'email' => 'clero90209575@diu.edu.bd',
                'student_id' => '90209575',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'BBA',
                'batch' => '40',
                'semester' => '5th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            22 => 
            array (
                'id' => 27,
                'name' => 'Freida Rippin',
                'email' => 'freri47244641@diu.edu.bd',
                'student_id' => '47244641',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'EEE',
                'batch' => '39',
                'semester' => '3th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            23 => 
            array (
                'id' => 28,
                'name' => 'Carolina Stehr',
                'email' => 'carst68866840@diu.edu.bd',
                'student_id' => '68866840',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'CSE',
                'batch' => '40',
                'semester' => '5th',
                'section' => 'A',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            24 => 
            array (
                'id' => 29,
                'name' => 'Adriana Cruickshank',
                'email' => 'adrcr19692739@diu.edu.bd',
                'student_id' => '19692739',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'Pharmacy',
                'batch' => '41',
                'semester' => '7th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            25 => 
            array (
                'id' => 30,
                'name' => 'Lora Lynch',
                'email' => 'lorly98101698@diu.edu.bd',
                'student_id' => '98101698',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'English',
                'batch' => '42',
                'semester' => '5th',
                'section' => 'A',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            26 => 
            array (
                'id' => 31,
                'name' => 'Davon Fay',
                'email' => 'davfa39449440@diu.edu.bd',
                'student_id' => '39449440',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'EEE',
                'batch' => '39',
                'semester' => '1th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            27 => 
            array (
                'id' => 32,
            'name' => 'Madisyn Fay (CR)',
                'email' => 'cr.madfa72167992@diu.edu.bd',
                'student_id' => '72167992',
                'role' => 'cr',
                'is_approved' => 1,
                'department' => 'English',
                'batch' => '42',
                'semester' => '2th',
                'section' => 'C',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            28 => 
            array (
                'id' => 33,
            'name' => 'Hosea Macejkovic (CR)',
                'email' => 'cr.hosma33094793@diu.edu.bd',
                'student_id' => '33094793',
                'role' => 'cr',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '42',
                'semester' => '6th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            29 => 
            array (
                'id' => 34,
            'name' => 'Clinton Reichel (CR)',
                'email' => 'cr.clire93540918@diu.edu.bd',
                'student_id' => '93540918',
                'role' => 'cr',
                'is_approved' => 1,
                'department' => 'EEE',
                'batch' => '40',
                'semester' => '8th',
                'section' => 'A',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            30 => 
            array (
                'id' => 35,
            'name' => 'London Runolfsson (CR)',
                'email' => 'cr.lonru65439728@diu.edu.bd',
                'student_id' => '65439728',
                'role' => 'cr',
                'is_approved' => 1,
                'department' => 'Pharmacy',
                'batch' => '41',
                'semester' => '8th',
                'section' => 'C',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            31 => 
            array (
                'id' => 36,
            'name' => 'Clay Hills (CR)',
                'email' => 'cr.clahi58516478@diu.edu.bd',
                'student_id' => '58516478',
                'role' => 'cr',
                'is_approved' => 1,
                'department' => 'SWE',
                'batch' => '42',
                'semester' => '3th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => '2026-03-26 09:44:13',
                'password' => '$2y$12$NyD.7FeVCJkBCCxz3NZl9.xZ3ms9AVmI2ODZ6iqjnn2504c4Yek1q',
                'remember_token' => NULL,
                'created_at' => '2026-03-26 09:44:13',
                'updated_at' => '2026-03-26 09:44:13',
            ),
            32 => 
            array (
                'id' => 37,
                'name' => 'Unique User',
                'email' => 'unique999@test.com',
                'student_id' => '999999',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'CSE',
                'batch' => '2021',
                'semester' => '5th',
                'section' => 'A',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$s/YB2oBv6b23II.XuNYFFu11f9PDc.mZ7zYKkpg4ogdadQ5ZAuXMO',
                'remember_token' => NULL,
                'created_at' => '2026-04-04 23:00:01',
                'updated_at' => '2026-04-04 23:00:01',
            ),
            33 => 
            array (
                'id' => 38,
                'name' => 'Mehedi Hasan Jony',
                'email' => 'jony0242320005341134@diu.edu.bd',
                'student_id' => '0242320005341134',
                'role' => 'student',
                'is_approved' => 1,
                'department' => 'CIS',
                'batch' => '41',
                'semester' => '6th',
                'section' => 'D',
                'profile_image' => 'profile_images/orUyYYzGdQLdQ8WPmUgzAjDQ8GnL30D4WQMGpKCQ.jpg',
                'major' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$FTk69Cnnr5a3uHbzEtxT.ugmiHy3/8c1U2cCedbBGVtOlimI7msku',
                'remember_token' => NULL,
                'created_at' => '2026-04-11 23:53:30',
                'updated_at' => '2026-04-11 23:53:52',
            ),
            34 => 
            array (
                'id' => 39,
                'name' => 'Mahfuz Emon',
                'email' => 'mahfuz0242310005341234@diu.edu.bd',
                'student_id' => '0242310005341234',
                'role' => 'cr',
                'is_approved' => 1,
                'department' => 'CIS',
                'batch' => '41',
                'semester' => '6th',
                'section' => 'D',
                'profile_image' => NULL,
                'major' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$12$nAlEtBWO8v4BGgq5DpeeMOgT1KZ1MTBK0M.1SpezdcnR507k3/KKC',
                'remember_token' => NULL,
                'created_at' => '2026-04-12 00:02:21',
                'updated_at' => '2026-04-12 00:04:09',
            ),
        ));
        
        
    }
}